"""
Chat request and response schemas.

These schemas define the request and response
models used by the Chat API.
"""

from pydantic import BaseModel, Field


class ChatRequest(BaseModel):
    """
    Incoming chat request.
    """

    session_id: str = Field(
        ...,
        description="Unique identifier for the conversation session.",
        examples=["mahdi-session"],
    )

    message: str = Field(
        ...,
        description="User message.",
        examples=["Hello!"],
    )


class ChatResponse(BaseModel):
    """
    Chat response returned by the API.
    """

    user_message: str = Field(
        ...,
        description="Original user message.",
    )

    ai_response: str = Field(
        ...,
        description="Response generated by the AI model.",
    )